#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub enum FlagEffect {
    Set,
    Unset,
    Conditional,
    NoEffect,
}
pub const T: FlagEffect = FlagEffect::Set;
pub const F: FlagEffect = FlagEffect::Unset;
pub const A: FlagEffect = FlagEffect::Conditional;
pub const B: FlagEffect = FlagEffect::NoEffect;

pub const CLOCK:[u8; 256] = [
 4, 12,  8,  8,  4,  4,  8,  4, 20,  8,  8,  8,  4,  4,  8,  4, 
 4, 12,  8,  8,  4,  4,  8,  4, 12,  8,  8,  8,  4,  4,  8,  4, 
 8, 12,  8,  8,  4,  4,  8,  4,  8,  8,  8,  8,  4,  4,  8,  4, 
 8, 12,  8,  8, 12, 12, 12,  4,  8,  8,  8,  8,  4,  4,  8,  4, 
 4,  4,  4,  4,  4,  4,  8,  4,  4,  4,  4,  4,  4,  4,  8,  4, 
 4,  4,  4,  4,  4,  4,  8,  4,  4,  4,  4,  4,  4,  4,  8,  4, 
 4,  4,  4,  4,  4,  4,  8,  4,  4,  4,  4,  4,  4,  4,  8,  4, 
 8,  8,  8,  8,  8,  8,  4,  8,  4,  4,  4,  4,  4,  4,  8,  4, 
 4,  4,  4,  4,  4,  4,  8,  4,  4,  4,  4,  4,  4,  4,  8,  4, 
 4,  4,  4,  4,  4,  4,  8,  4,  4,  4,  4,  4,  4,  4,  8,  4, 
 4,  4,  4,  4,  4,  4,  8,  4,  4,  4,  4,  4,  4,  4,  8,  4, 
 4,  4,  4,  4,  4,  4,  8,  4,  4,  4,  4,  4,  4,  4,  8,  4, 
 8, 12, 12, 16, 12, 16,  8, 16,  8, 16, 12,  4, 12, 24,  8, 16, 
 8, 12, 12,  4, 12, 16,  8, 16,  8, 16, 12,  4, 12,  4,  8, 16, 
12, 12,  8,  4,  4, 16,  8, 16, 16,  4, 16,  4,  4,  4,  8, 16, 
12, 12,  8,  4,  4, 16,  8, 16, 12,  8, 16,  4,  4,  4,  8, 16, 
];
pub const ALT_CLOCK:[u8; 256] = [
 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
12,  0,  0,  0,  0,  0,  0,  0, 12,  0,  0,  0,  0,  0,  0,  0, 
12,  0,  0,  0,  0,  0,  0,  0, 12,  0,  0,  0,  0,  0,  0,  0, 
 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
20,  0, 16,  0, 24,  0,  0,  0, 20,  0, 16,  0, 24,  0,  0,  0, 
20,  0, 16,  0, 24,  0,  0,  0, 20,  0, 16,  0, 24,  0,  0,  0, 
 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
];
pub const CB_CLOCK:[u8; 256] = [
 8,  8,  8,  8,  8,  8, 16,  8,  8,  8,  8,  8,  8,  8, 16,  8, 
 8,  8,  8,  8,  8,  8, 16,  8,  8,  8,  8,  8,  8,  8, 16,  8, 
 8,  8,  8,  8,  8,  8, 16,  8,  8,  8,  8,  8,  8,  8, 16,  8, 
 8,  8,  8,  8,  8,  8, 16,  8,  8,  8,  8,  8,  8,  8, 16,  8, 
 8,  8,  8,  8,  8,  8, 12,  8,  8,  8,  8,  8,  8,  8, 12,  8, 
 8,  8,  8,  8,  8,  8, 12,  8,  8,  8,  8,  8,  8,  8, 12,  8, 
 8,  8,  8,  8,  8,  8, 12,  8,  8,  8,  8,  8,  8,  8, 12,  8, 
 8,  8,  8,  8,  8,  8, 12,  8,  8,  8,  8,  8,  8,  8, 12,  8, 
 8,  8,  8,  8,  8,  8, 16,  8,  8,  8,  8,  8,  8,  8, 16,  8, 
 8,  8,  8,  8,  8,  8, 16,  8,  8,  8,  8,  8,  8,  8, 16,  8, 
 8,  8,  8,  8,  8,  8, 16,  8,  8,  8,  8,  8,  8,  8, 16,  8, 
 8,  8,  8,  8,  8,  8, 16,  8,  8,  8,  8,  8,  8,  8, 16,  8, 
 8,  8,  8,  8,  8,  8, 16,  8,  8,  8,  8,  8,  8,  8, 16,  8, 
 8,  8,  8,  8,  8,  8, 16,  8,  8,  8,  8,  8,  8,  8, 16,  8, 
 8,  8,  8,  8,  8,  8, 16,  8,  8,  8,  8,  8,  8,  8, 16,  8, 
 8,  8,  8,  8,  8,  8, 16,  8,  8,  8,  8,  8,  8,  8, 16,  8, 
];
pub const ZERO_FLAG:[FlagEffect; 256] = [
B, B, B, B, A, A, B, F, B, B, B, B, A, A, B, F, 
B, B, B, B, A, A, B, F, B, B, B, B, A, A, B, F, 
B, B, B, B, A, A, B, A, B, B, B, B, A, A, B, B, 
B, B, B, B, A, A, B, B, B, B, B, B, A, A, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, 
A, A, A, A, A, A, A, T, A, A, A, A, A, A, A, A, 
A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, T, 
A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, T, 
B, B, B, B, B, B, A, B, B, B, B, B, B, B, A, B, 
B, B, B, B, B, B, A, B, B, B, B, B, B, B, A, B, 
B, B, B, B, B, B, A, B, F, B, B, B, B, B, A, B, 
B, A, B, B, B, B, A, B, F, B, B, B, B, B, A, B, 
];
pub const SUB_FLAG:[FlagEffect; 256] = [
B, B, B, B, F, T, B, F, B, F, B, B, F, T, B, F, 
B, B, B, B, F, T, B, F, B, F, B, B, F, T, B, F, 
B, B, B, B, F, T, B, B, B, F, B, B, F, T, B, T, 
B, B, B, B, F, T, B, F, B, F, B, B, F, T, B, F, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, 
T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, 
F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, 
F, F, F, F, F, F, F, F, T, T, T, T, T, T, T, T, 
B, B, B, B, B, B, F, B, B, B, B, B, B, B, F, B, 
B, B, B, B, B, B, T, B, B, B, B, B, B, B, T, B, 
B, B, B, B, B, B, F, B, F, B, B, B, B, B, F, B, 
B, A, B, B, B, B, F, B, F, B, B, B, B, B, T, B, 
];
pub const HALF_FLAG:[FlagEffect; 256] = [
B, B, B, B, A, A, B, F, B, A, B, B, A, A, B, F, 
B, B, B, B, A, A, B, F, B, A, B, B, A, A, B, F, 
B, B, B, B, A, A, B, F, B, A, B, B, A, A, B, T, 
B, B, B, B, A, A, B, F, B, A, B, B, A, A, B, F, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, 
A, A, A, A, A, A, A, F, A, A, A, A, A, A, A, A, 
T, T, T, T, T, T, T, T, F, F, F, F, F, F, F, F, 
F, F, F, F, F, F, F, F, A, A, A, A, A, A, A, F, 
B, B, B, B, B, B, A, B, B, B, B, B, B, B, A, B, 
B, B, B, B, B, B, A, B, B, B, B, B, B, B, A, B, 
B, B, B, B, B, B, T, B, A, B, B, B, B, B, F, B, 
B, A, B, B, B, B, F, B, A, B, B, B, B, B, A, B, 
];
pub const CARRY_FLAG:[FlagEffect; 256] = [
B, B, B, B, B, B, B, A, B, A, B, B, B, B, B, A, 
B, B, B, B, B, B, B, A, B, A, B, B, B, B, B, A, 
B, B, B, B, B, B, B, A, B, A, B, B, B, B, B, B, 
B, B, B, B, B, B, B, T, B, A, B, B, B, B, B, A, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, 
A, A, A, A, A, A, A, F, A, A, A, A, A, A, A, B, 
F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, 
F, F, F, F, F, F, F, F, A, A, A, A, A, A, A, F, 
B, B, B, B, B, B, A, B, B, B, B, B, B, B, A, B, 
B, B, B, B, B, B, A, B, B, B, B, B, B, B, A, B, 
B, B, B, B, B, B, F, B, A, B, B, B, B, B, F, B, 
B, A, B, B, B, B, F, B, A, B, B, B, B, B, A, B, 
];
pub const CB_ZERO_FLAG:[FlagEffect; 256] = [
A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, 
A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, 
A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, 
A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, 
A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, 
A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, 
A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, 
A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
];
pub const CB_SUB_FLAG:[FlagEffect; 256] = [
F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, 
F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, 
F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, 
F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, 
F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, 
F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, 
F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, 
F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
];
pub const CB_HALF_FLAG:[FlagEffect; 256] = [
F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, 
F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, 
F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, 
F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, 
T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, 
T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, 
T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, 
T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
];
pub const CB_CARRY_FLAG:[FlagEffect; 256] = [
A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, 
A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, 
A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, 
F, F, F, F, F, F, F, F, A, A, A, A, A, A, A, A, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 
];
